# Generated by Django 4.2.30 on 2026-05-12 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labtests', '0001_initial'),
        ('patients', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtests.assaymaster')),
            ],
            options={
                'db_table': 'order_line',
            },
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.PositiveSmallIntegerField(choices=[(1, 'Ordered'), (2, 'Collected'), (3, 'In-Lab'), (4, 'Completed')], default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assays', models.ManyToManyField(related_name='orders', through='orders.OrderLine', to='labtests.assaymaster')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_collected', to='accounts.userprofile')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_placed', to='accounts.userprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='patients.patientmaster')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_received', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'order_transaction',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.ordertransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together={('order', 'assay')},
        ),
    ]
